name: GitHub to GitHub

on:
  push:
    branches:
    - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login Source GitHub
        run: |
          gh --version
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Mirror Github master test
        uses: CynicalSloths/action-mirror-git@main
        with:
          source_protocol: https
          source_host: github.com
          source_username: CynicalSloths
          source_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_name: cynicalsloths.github.io-drafts
          dest_protocol: https
          dest_host: github.com
          dest_username: CynicalSloths
          dest_token: ${{ secrets.DEST_TOKEN_GITHUB }}
          dest_repo_name: cynicalsloths.github.io
          push_branch_only: true
          push_branch_name: master
          notify_prefix: "Mirror Action on Github"
          ignore_error: "true"
